# Generated by Django 3.1.7 on 2021-02-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-name']},
        ),
    ]
