# Generated by Django 3.1.7 on 2021-04-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_film_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Žánr', 'verbose_name_plural': 'Žánry'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='attachment',
            order_with_respect_to='film',
        ),
    ]
